### ISSUE TITLE
Latest version shows "This version of Signal Desktop has expired"

### ISSUE THREAD

**Issue by maximbaz** [0mniteck/Signal-Desktop-Mobian#15]
Hey, first of all thanks for building these packages, really helps aarch64 users!

I was wondering if you experience the same, launching Signal from the two latest releases in this repo instantly show "This version of Signal Desktop has expired" on launch, even though neither `7.31` nor `7.33` are likely meant to be banned just yet.

If I build the artifacts locally using your tooling from this repo, everything works fine, I don't get any warnings - I wonder what could be the reason, could it e.g. be caused by you and me using different values for `$SOURCE_DATE_EPOCH`?

Here locally I literally just run these 3 commands:

```
export SOURCE_DATE_EPOCH=$(date +%s)

docker build -t signal-desktop \
  --build-arg SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH \
  --build-arg NODE_VERSION=20.18.0 \
  --build-arg NVM_VERSION=0.40.1 \
  --build-arg NPM_VERSION=10.2.5 .

docker run -it --cpus=$(nproc) \
  --name signal-desktop \
  -e NPM_CONFIG_CACHE=/tmp/.npm-cache \
  -e SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH \
  signal-desktop public
``` 

P.S. Not that important perhaps but just fyi, a command to generate a new signing key has changed, I tried to update it like below but I don't think it actually works - maybe it's a step in the right direction.

```patch
--- a/signal-buildscript.sh
+++ b/signal-buildscript.sh
@@ -81,7 +81,7 @@ pushd /Signal-Desktop
   debpath=$(ls /Signal-Desktop/release/signal-desktop_*)
   if [ ! -f /Signal-Desktop/release/.private.key ]; then
     echo "Generating New Keypair."
-    npm run ts/updater/generateKeyPair.js -- --key /Signal-Desktop/release/public.key --private /Signal-Desktop/release/.private.key
+    ./node_modules/.bin/ts-node ts/updater/generateKeyPair.ts -- --key /Signal-Desktop/release/public.key --private /Signal-Desktop/release/.private.key
     echo "Signing Release."
     npm run sign-release -- --private /Signal-Desktop/release/.private.key --update $debpath
   else
```

**Comment by 0mniteck** [comment]
Released https://github.com/0mniteck/Signal-Desktop-Mobian/releases/tag/7.33.1

I will try to figure out what the exact expiry period is
