### ISSUE TITLE
apt sources location

### ISSUE THREAD

**Issue by fommil** [0mniteck/Signal-Desktop-Mobian#7]
Hi, thank you for making these .debs available! I'm using these on a Debian Trixie install on an ARM64 laptop (Pinebook Pro).

Are you publishing them to a location that is compatible with apt sources so that the apt package manager can keep them up to date automatically?

**Comment by 0mniteck** [comment]
https://github.com/users/0mniteck/projects/2?pane=issue&itemId=46441354
