### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by teutat3s** [0mniteck/Signal-Desktop-Mobian#8]
Hello,
thank you for creating a signal-desktop package for linux aarch64. Sadly it's currently unusable because the version 7.5.1 is expired and  signal refuses to send messages. Could you release a new version or is this project no longer maintained?

**Comment by 0mniteck** [comment]
I appologize was on vacation, resuming regularly scheduled builds today

**Comment by 0mniteck** [comment]
Build is processing now will test on-device and publish v7.19.0 in the AM tomorrow. Thanks for the patience and apologies for the delayed releases and any issues it may have caused.

**Comment by 0mniteck** [comment]
v7.19.0 has been released
